name: kerala_krishi_sahayak
description: AI-Powered Farming Assistant for Kerala Farmers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Image handling
  image_picker: ^1.0.4
  
  # HTTP requests (for future API integration)
  http: ^1.1.0
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # Custom fonts temporarily disabled because font files are not present.
  # To re-enable, add the files under assets/fonts/ and restore the section below.
  # fonts:
  #   - family: FKGroteskNeue
  #     fonts:
  #       - asset: assets/fonts/FKGroteskNeue-Regular.ttf
  #       - asset: assets/fonts/FKGroteskNeue-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/FKGroteskNeue-Bold.ttf
  #         weight: 700
